import { RegionalTariffs } from "@/types/tariff";

export const flatTariffs: RegionalTariffs[] = [
  {
    regionId: "naro-fominsk",
    plans: [
      {
        id: "nf-base",
        name: "БАЗОВЫЙ",
        speed: 50,
        price: 650,
        features: ["Безлимитный интернет", "Wi-Fi роутер в аренду"],
        technology: "ethernet",
      },
      {
        id: "nf-optimal",
        name: "ОПТИМАЛЬНЫЙ",
        speed: 100,
        price: 800,
        isHit: true,
        tvChannels: 198,
        features: ["Безлимитный интернет", "198 каналов ТВ", "Wi-Fi роутер в аренду", "ТВ-приставка в аренду"],
        technology: "ethernet",
      },
      {
        id: "nf-success",
        name: "УСПЕШНЫЙ",
        speed: 300,
        price: 1050,
        tvChannels: 269,
        features: ["Безлимитный интернет", "269 каналов ТВ", "Wi-Fi роутер в аренду", "ТВ-приставка в аренду"],
        technology: "ethernet",
      },
    ],
  },
  {
    regionId: "odintsovo",
    plans: [
      {
        id: "od-50",
        name: "СТРИМЛАЙН-50",
        speed: 50,
        price: 450,
        features: ["Безлимитный интернет 50 Мбит/с"],
        technology: "gpon",
      },
      {
        id: "od-100",
        name: "СТРИМЛАЙН-100",
        speed: 100,
        price: 550,
        isHit: true,
        features: ["Безлимитный интернет 100 Мбит/с"],
        technology: "gpon",
      },
      {
        id: "od-300",
        name: "СТРИМЛАЙН-300",
        speed: 300,
        price: 800,
        features: ["Безлимитный интернет 300 Мбит/с"],
        technology: "gpon",
      },
      {
        id: "od-tv",
        name: "СТРИМЛАЙН + ТВ",
        speed: 100,
        price: 750,
        tvChannels: 260,
        features: ["Безлимитный интернет 100 Мбит/с", "260 каналов ТВ"],
        technology: "gpon",
      },
    ],
  },
  {
    regionId: "kievskiy",
    plans: [
      {
        id: "kv-base",
        name: "БАЗОВЫЙ",
        speed: 50,
        price: 650,
        features: ["Безлимитный интернет", "Wi-Fi роутер в аренду"],
      },
      {
        id: "kv-optimal",
        name: "ОПТИМАЛЬНЫЙ",
        speed: 100,
        price: 800,
        isHit: true,
        tvChannels: 198,
        features: ["Безлимитный интернет", "198 каналов ТВ", "Wi-Fi роутер в аренду"],
      },
      {
        id: "kv-success",
        name: "УСПЕШНЫЙ",
        speed: 300,
        price: 1050,
        tvChannels: 269,
        features: ["Безлимитный интернет", "269 каналов ТВ", "Wi-Fi роутер в аренду"],
      },
    ],
  },
  {
    regionId: "kalininets",
    plans: [
      {
        id: "kl-50",
        name: "СТРИМЛАЙН-50",
        speed: 50,
        price: 450,
        features: ["Безлимитный интернет 50 Мбит/с"],
      },
      {
        id: "kl-100",
        name: "СТРИМЛАЙН-100",
        speed: 100,
        price: 550,
        isHit: true,
        features: ["Безлимитный интернет 100 Мбит/с"],
      },
      {
        id: "kl-300",
        name: "СТРИМЛАЙН-300",
        speed: 300,
        price: 800,
        features: ["Безлимитный интернет 300 Мбит/с"],
      },
      {
        id: "kl-tv",
        name: "СТРИМЛАЙН + ТВ",
        speed: 100,
        price: 750,
        tvChannels: 260,
        features: ["Безлимитный интернет 100 Мбит/с", "260 каналов ТВ"],
      },
    ],
  },
  {
    regionId: "yakovlevskoe",
    plans: [
      {
        id: "yk-50",
        name: "СТРИМЛАЙН-50",
        speed: 50,
        price: 450,
        features: ["Безлимитный интернет 50 Мбит/с"],
      },
      {
        id: "yk-100",
        name: "СТРИМЛАЙН-100",
        speed: 100,
        price: 550,
        isHit: true,
        features: ["Безлимитный интернет 100 Мбит/с"],
      },
      {
        id: "yk-300",
        name: "СТРИМЛАЙН-300",
        speed: 300,
        price: 800,
        features: ["Безлимитный интернет 300 Мбит/с"],
      },
      {
        id: "yk-tv",
        name: "СТРИМЛАЙН + ТВ",
        speed: 100,
        price: 750,
        tvChannels: 260,
        features: ["Безлимитный интернет 100 Мбит/с", "260 каналов ТВ"],
      },
    ],
  },
  {
    regionId: "borisoglebskoe",
    plans: [
      {
        id: "bg-bronze",
        name: "Bronze",
        speed: 100,
        price: 700,
        features: ["Безлимитный интернет"],
      },
      {
        id: "bg-silver",
        name: "Silver",
        speed: 300,
        price: 800,
        isHit: true,
        tvChannels: 198,
        features: ["Безлимитный интернет", "198 каналов ТВ"],
      },
      {
        id: "bg-gold",
        name: "Gold",
        speed: 500,
        price: 1000,
        tvChannels: 300,
        features: ["Безлимитный интернет", "300 каналов ТВ"],
      },
    ],
  },
];
